Repository M7hesh/reverse-shell-cheat-sheet, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  One-Liners-cheatsheet-by-pentest-monkey.txt
Labels: enhancement, good first issue, hacktoberfest-accepted

#2 cheatsheet updated
  One-Liners-cheatsheet-by-pentest-monkey.txt
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 updated file
  One-Liners-cheatsheet-by-pentest-monkey.txt
Labels: enhancement, hacktoberfest-accepted

#4 Added Netcat reverse shell code
  One-Liners-cheatsheet-by-pentest-monkey.txt
Labels: enhancement, hacktoberfest-accepted

#6 Update One-Liners-cheatsheet-by-pentest-monkey.txt
  One-Liners-cheatsheet-by-pentest-monkey.txt
Labels: documentation, enhancement, hacktoberfest-accepted
